version: "3.9"

services:
  app:
    build: .
    command: /bin/bash -c "tail -F anything"
    container_name: base_fastapi
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - "./:/var/www/base_fastapi"
